query Page($slug: String, $locale: SiteLocale) {
  page(filter: { slug: { eq: $slug } }, locale: $locale) {
    title
    pageBuilder {
      pageBuilder {
        ...PageBuilderFragment
      }
    }
  }
}
